## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `np.concatenate()`: Method to concatenate two or more arrays
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [3]:
import numpy as np

In [19]:
a = np.random.randint(10,50, size = (5,2,3))

In [20]:
a.shape

(5, 2, 3)

In [21]:
a.ndim

3

In [22]:
a.dtype

dtype('int64')

In [23]:
a.size #Number of elements

30

In [24]:
a.T

array([[[10, 40, 22, 46, 23],
        [11, 47, 31, 46, 28]],

       [[29, 23, 27, 13, 18],
        [12, 44, 11, 20, 36]],

       [[30, 22, 30, 29, 25],
        [48, 25, 46, 16, 38]]])

In [25]:
a.shape

(5, 2, 3)

In [29]:
a.reshape(2,3,5)

array([[[10, 29, 30, 11, 12],
        [48, 40, 23, 22, 47],
        [44, 25, 22, 27, 30]],

       [[31, 11, 46, 46, 13],
        [29, 46, 20, 16, 23],
        [18, 25, 28, 36, 38]]])

In [30]:
a.reshape(-1,3,5)

array([[[10, 29, 30, 11, 12],
        [48, 40, 23, 22, 47],
        [44, 25, 22, 27, 30]],

       [[31, 11, 46, 46, 13],
        [29, 46, 20, 16, 23],
        [18, 25, 28, 36, 38]]])

In [31]:
a.ravel()

array([10, 29, 30, 11, 12, 48, 40, 23, 22, 47, 44, 25, 22, 27, 30, 31, 11,
       46, 46, 13, 29, 46, 20, 16, 23, 18, 25, 28, 36, 38])

In [33]:
a.flatten()

array([10, 29, 30, 11, 12, 48, 40, 23, 22, 47, 44, 25, 22, 27, 30, 31, 11,
       46, 46, 13, 29, 46, 20, 16, 23, 18, 25, 28, 36, 38])

In [50]:
b = np.random.randint(1,10, (2,3))
c = np.random.randint(1,10, (2,3))
b, c

(array([[8, 1, 4],
        [6, 4, 3]]),
 array([[1, 1, 9],
        [6, 8, 5]]))

### 0 > column wise > vsatck
### 1 > row wise > hstack

In [51]:
d= np.concatenate([b,c],axis=0)
d

array([[8, 1, 4],
       [6, 4, 3],
       [1, 1, 9],
       [6, 8, 5]])

In [53]:
np.vstack((b,c))

array([[8, 1, 4],
       [6, 4, 3],
       [1, 1, 9],
       [6, 8, 5]])

In [55]:
np.hstack((b,c))

array([[8, 1, 4, 1, 1, 9],
       [6, 4, 3, 6, 8, 5]])

In [59]:
np.split(d,3, axis=1)

[array([[8],
        [6],
        [1],
        [6]]),
 array([[1],
        [4],
        [1],
        [8]]),
 array([[4],
        [3],
        [9],
        [5]])]