In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.6'

## Creating Numpy Array

In [4]:
list1 = [[2,3,4]]

In [5]:
arr1 = np.array(list1)

In [6]:
arr1

array([[2, 3, 4]])

In [7]:
arr1.shape

(1, 3)

In [8]:
arr1.ndim

2

In [9]:
list1 = [[2,3,4],
        [6,7,8],
        [3,5,6]]
arr2 = np.array(list1)

In [10]:
arr2

array([[2, 3, 4],
       [6, 7, 8],
       [3, 5, 6]])

In [11]:
arr2.shape

(3, 3)

In [12]:
arr2.ndim

2

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [13]:
np.zeros(shape = (4,4), dtype = "int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.ones(shape = (2, 3,3), dtype="int8")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [15]:
np.full(shape=(3,4), fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [16]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [17]:
np.linspace((0,1,2),(10,20,30) ,num=20)

array([[ 0.        ,  1.        ,  2.        ],
       [ 0.52631579,  2.        ,  3.47368421],
       [ 1.05263158,  3.        ,  4.94736842],
       [ 1.57894737,  4.        ,  6.42105263],
       [ 2.10526316,  5.        ,  7.89473684],
       [ 2.63157895,  6.        ,  9.36842105],
       [ 3.15789474,  7.        , 10.84210526],
       [ 3.68421053,  8.        , 12.31578947],
       [ 4.21052632,  9.        , 13.78947368],
       [ 4.73684211, 10.        , 15.26315789],
       [ 5.26315789, 11.        , 16.73684211],
       [ 5.78947368, 12.        , 18.21052632],
       [ 6.31578947, 13.        , 19.68421053],
       [ 6.84210526, 14.        , 21.15789474],
       [ 7.36842105, 15.        , 22.63157895],
       [ 7.89473684, 16.        , 24.10526316],
       [ 8.42105263, 17.        , 25.57894737],
       [ 8.94736842, 18.        , 27.05263158],
       [ 9.47368421, 19.        , 28.52631579],
       [10.        , 20.        , 30.        ]])

In [18]:
np.random.randint(0,10, size = (2,2))

array([[9, 3],
       [5, 5]])

In [19]:
np.ones(shape = (2, 2, 1, 3), dtype="int8")

array([[[[1, 1, 1]],

        [[1, 1, 1]]],


       [[[1, 1, 1]],

        [[1, 1, 1]]]], dtype=int8)

## Accessing an Array

## Indexing and Slicing NumPy Arrays

NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

### Indexing:

Indexing follows a simple rule that we may have encountered before. Let's give it a try.

- 1D Array: array_name[idx] (Similar to Python list)
- 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
- ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

**OR**

- 2D Array: array_name[row_idx][col_idx]
- ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]


 ### Slicing:

Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

- 1D Array: array_name[idx1:idx2:step]
- 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
- ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [20]:
#1D
a = np.array([1,2,3,4,5])

In [21]:
a[-3]

np.int64(3)

In [22]:
a[::-1]

array([5, 4, 3, 2, 1])

In [23]:
#2D
b = np.random.randint(0,25, size=(3,3))

In [24]:
b

array([[16,  3, 11],
       [20, 10,  7],
       [16,  2, 20]])

In [25]:
b[1,0]

np.int64(20)

In [26]:
b[-1,0] #or b[-1][0]

np.int64(16)

In [27]:
# Slicing 2D array : (array[<row_slice>, <col_slice>])
b[1,:3]

array([20, 10,  7])

In [28]:
b[:,2]

array([11,  7, 20])

In [29]:
#3D
c = np.random.randint(0,25, size=(3,3,2))

In [30]:
c

array([[[21, 10],
        [18,  9],
        [24, 24]],

       [[ 2, 14],
        [20,  1],
        [ 7, 12]],

       [[ 4, 24],
        [13,  8],
        [ 9,  8]]])

In [31]:
c[0, 2, 1]

np.int64(24)

In [32]:
c[0]

array([[21, 10],
       [18,  9],
       [24, 24]])

In [33]:
c[0][2]

array([24, 24])

In [34]:
c[0][2][1]

np.int64(24)

In [35]:
c

array([[[21, 10],
        [18,  9],
        [24, 24]],

       [[ 2, 14],
        [20,  1],
        [ 7, 12]],

       [[ 4, 24],
        [13,  8],
        [ 9,  8]]])

In [36]:
c[:,2,:]

array([[24, 24],
       [ 7, 12],
       [ 9,  8]])

In [37]:
dataset = np.random.randint(0,100, (1600,25))

In [38]:
dataset.shape

(1600, 25)

In [39]:
image_dataset = np.random.randint(0,255, (16,3,720,720))

In [40]:
image_dataset[1, 0, :,:]

array([[ 51, 253,  46, ..., 125, 231,  20],
       [120, 240, 185, ...,  98, 202, 135],
       [ 18,  74, 137, ...,  10, 219, 154],
       ...,
       [ 44, 222,  15, ...,   6, 223, 211],
       [190,  41,  95, ..., 212,  12, 159],
       [ 76, 141,  17, ..., 147, 140,  95]], shape=(720, 720))

### Boolean or Mask Indexing:

Boolean or mask indexing is a powerful feature in NumPy that allows you to use boolean arrays (or masks) to select elements from another array. The basic idea behind boolean indexing is to create a boolean array with the same shape as the array you want to select from, where each element of the boolean array corresponds to whether or not you want to select the corresponding element from the other array.

In [41]:
a = np.random.randint(1,10,(5,5))
a

array([[8, 1, 7, 7, 3],
       [9, 7, 2, 9, 6],
       [6, 1, 2, 2, 4],
       [8, 2, 8, 9, 3],
       [6, 1, 4, 1, 7]])

In [42]:
mask = a > 5

In [43]:
mask

array([[ True, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [ True, False, False, False, False],
       [ True, False,  True,  True, False],
       [ True, False, False, False,  True]])

In [44]:
a[mask]

array([8, 7, 7, 9, 7, 9, 6, 6, 8, 8, 9, 6, 7])

In [45]:
mask = [True, False, False, True, True]

In [46]:
a[:,mask]

array([[8, 7, 3],
       [9, 9, 6],
       [6, 2, 4],
       [8, 9, 3],
       [6, 1, 7]])

In [47]:
a

array([[8, 1, 7, 7, 3],
       [9, 7, 2, 9, 6],
       [6, 1, 2, 2, 4],
       [8, 2, 8, 9, 3],
       [6, 1, 4, 1, 7]])