## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `np.concatenate()`: Method to concatenate two or more arrays
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,50, size = (5,2,3))

In [3]:
a.shape

(5, 2, 3)

In [4]:
a.ndim

3

In [5]:
a.dtype

dtype('int64')

In [6]:
a.size #Number of elements

30

In [7]:
a.T

array([[[11, 31, 14, 19, 39],
        [46, 34, 42, 33, 32]],

       [[44, 32, 47, 28, 41],
        [29, 27, 47, 12, 42]],

       [[34, 23, 49, 34, 24],
        [33, 12, 25, 21, 33]]])

In [8]:
a.shape

(5, 2, 3)

In [9]:
a.reshape(2,3,5)

array([[[11, 44, 34, 46, 29],
        [33, 31, 32, 23, 34],
        [27, 12, 14, 47, 49]],

       [[42, 47, 25, 19, 28],
        [34, 33, 12, 21, 39],
        [41, 24, 32, 42, 33]]])

In [10]:
a.reshape(-1,3,5)

array([[[11, 44, 34, 46, 29],
        [33, 31, 32, 23, 34],
        [27, 12, 14, 47, 49]],

       [[42, 47, 25, 19, 28],
        [34, 33, 12, 21, 39],
        [41, 24, 32, 42, 33]]])

In [11]:
a.ravel()

array([11, 44, 34, 46, 29, 33, 31, 32, 23, 34, 27, 12, 14, 47, 49, 42, 47,
       25, 19, 28, 34, 33, 12, 21, 39, 41, 24, 32, 42, 33])

In [12]:
a.flatten()

array([11, 44, 34, 46, 29, 33, 31, 32, 23, 34, 27, 12, 14, 47, 49, 42, 47,
       25, 19, 28, 34, 33, 12, 21, 39, 41, 24, 32, 42, 33])

In [13]:
b = np.random.randint(1,10, (2,3))
c = np.random.randint(1,10, (2,3))
b, c

(array([[9, 7, 8],
        [6, 8, 9]]),
 array([[7, 6, 4],
        [5, 4, 2]]))

### 0 > column wise > vsatck
### 1 > row wise > hstack

In [14]:
d= np.concatenate([b,c],axis=0)
d

array([[9, 7, 8],
       [6, 8, 9],
       [7, 6, 4],
       [5, 4, 2]])

In [15]:
np.vstack((b,c))

array([[9, 7, 8],
       [6, 8, 9],
       [7, 6, 4],
       [5, 4, 2]])

In [16]:
np.hstack((b,c))

array([[9, 7, 8, 7, 6, 4],
       [6, 8, 9, 5, 4, 2]])

In [17]:
np.split(d,3, axis=1)

[array([[9],
        [6],
        [7],
        [5]]),
 array([[7],
        [8],
        [6],
        [4]]),
 array([[8],
        [9],
        [4],
        [2]])]

In [32]:
z = np.random.randint(2,16, (4,6))
z

array([[ 9, 13,  9, 14,  8, 15],
       [ 9,  2, 13, 11,  6, 12],
       [ 5,  7,  7,  8, 12, 15],
       [ 3,  7,  2, 13,  2, 15]])

In [33]:
z.sum(axis = 0)

array([26, 29, 31, 46, 28, 57])

In [34]:
z.sum(axis = 1)

array([68, 53, 54, 42])

In [35]:
z.prod(axis  =0)

array([ 1215,  1274,  1638, 16016,  1152, 40500])

In [36]:
z.prod(axis = 1)

array([1769040,  185328,  352800,   16380])

In [37]:
z.cumsum(axis = 0)

array([[ 9, 13,  9, 14,  8, 15],
       [18, 15, 22, 25, 14, 27],
       [23, 22, 29, 33, 26, 42],
       [26, 29, 31, 46, 28, 57]])

In [38]:
z.min(axis= 1)

array([8, 2, 5, 2])

In [39]:
z.max(axis=0)

array([ 9, 13, 13, 14, 12, 15])

In [43]:
z.argmax(axis = 1) # index of max value

array([5, 2, 5, 5])

In [44]:
z.argmin(axis = 1) # # index of min value

array([4, 1, 0, 2])

In [45]:
z.clip(5,10)

array([[ 9, 10,  9, 10,  8, 10],
       [ 9,  5, 10, 10,  6, 10],
       [ 5,  7,  7,  8, 10, 10],
       [ 5,  7,  5, 10,  5, 10]])