## 1. Elementwise Operations

Refer to : https://numpy.org/doc/1.26/reference/array_api.html#elementwise-functions

In [1]:
import numpy as np

In [20]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[3,2,1],[9,8,1]])

In [13]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[3, 2, 1],
        [9, 8, 0]]))

### Arithmetic Operations

In [14]:
# a + b
np.add(a,b)

array([[ 7,  7,  7],
       [14, 15,  9]])

In [6]:
# a- b
np.subtract(a,b)

array([[ 1,  3,  5],
       [-4, -1,  9]])

In [15]:
# a * b
np.multiply(a,b)

array([[12, 10,  6],
       [45, 56,  0]])

In [18]:
# a ** 2
# np.square(a)
np.power(a, 2)

array([[16, 25, 36],
       [25, 49, 81]])

In [24]:
# a % b
quo, rem = np.divmod(a,b)

In [25]:
rem

array([[1, 1, 0],
       [5, 7, 0]])

### Trignometric

In [26]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427,  0.6569866 ,  0.41211849]])

In [28]:
new = 1 / np.tan(b)
new

array([[-7.01525255, -0.45765755,  0.64209262],
       [-2.21084541, -0.14706506,  0.64209262]])

### Rounding operations

In [31]:
# np.round(new, decimals=3)
np.around(new, decimals=3)

array([[-7.015, -0.458,  0.642],
       [-2.211, -0.147,  0.642]])

In [32]:
np.fix(new)

array([[-7., -0.,  0.],
       [-2., -0.,  0.]])

In [33]:
np.floor(new)

array([[-8., -1.,  0.],
       [-3., -1.,  0.]])

In [34]:
np.ceil(new)

array([[-7., -0.,  1.],
       [-2., -0.,  1.]])