In [3]:
!pip install numpy

In [8]:
import numpy as np

In [9]:
np.__version__

'2.2.6'

## Creating Numpy Array

In [24]:
list1 = [[2,3,4]]

In [25]:
arr1 = np.array(list1)

In [26]:
arr1

array([[2, 3, 4]])

In [27]:
arr1.shape

(1, 3)

In [28]:
arr1.ndim

2

In [30]:
list1 = [[2,3,4],
        [6,7,8],
        [3,5,6]]
arr2 = np.array(list1)

In [31]:
arr2

array([[2, 3, 4],
       [6, 7, 8],
       [3, 5, 6]])

In [32]:
arr2.shape

(3, 3)

In [33]:
arr2.ndim

2

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [35]:
np.zeros(shape = (4,4), dtype = "int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
np.ones(shape = (2, 3,3), dtype="int8")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [42]:
np.full(shape=(3,4), fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [45]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [53]:
np.linspace((0,1,2),(10,20,30) ,num=20)

array([[ 0.        ,  1.        ,  2.        ],
       [ 0.52631579,  2.        ,  3.47368421],
       [ 1.05263158,  3.        ,  4.94736842],
       [ 1.57894737,  4.        ,  6.42105263],
       [ 2.10526316,  5.        ,  7.89473684],
       [ 2.63157895,  6.        ,  9.36842105],
       [ 3.15789474,  7.        , 10.84210526],
       [ 3.68421053,  8.        , 12.31578947],
       [ 4.21052632,  9.        , 13.78947368],
       [ 4.73684211, 10.        , 15.26315789],
       [ 5.26315789, 11.        , 16.73684211],
       [ 5.78947368, 12.        , 18.21052632],
       [ 6.31578947, 13.        , 19.68421053],
       [ 6.84210526, 14.        , 21.15789474],
       [ 7.36842105, 15.        , 22.63157895],
       [ 7.89473684, 16.        , 24.10526316],
       [ 8.42105263, 17.        , 25.57894737],
       [ 8.94736842, 18.        , 27.05263158],
       [ 9.47368421, 19.        , 28.52631579],
       [10.        , 20.        , 30.        ]])

In [54]:
np.random.randint(0,10, size = (2,2))

array([[1, 4],
       [5, 2]])